<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralRepository extends \Doctrine\ORM\EntityRepository
{
  public function hasAny( $conditions=[]  )
    {
        $alias="u";
        $query =$this->createQueryBuilder('u');
        foreach ($conditions as $field  => $value) {
            $query
              ->andWhere("{$alias}.{$field}= :$field")
              ->setParameter( "$field" ,$value  );

        }
        return  $query->getQuery()
          ->getOneOrNullResult() !== NULL;

      }

}
