app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /{_locale}
    requirements:
      _locale: '%app_locales%'
    defaults:
      _locale: '%locale%'


_translation_edit_in_place:
    resource: '@TranslationBundle/Resources/config/routing_edit_in_place.yml'
    prefix:  /trans


logout:
    path: /logout


# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/cookbook/templating/render_without_controller.html
home:
    path: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    nim/inicio.html.twig
        _locale:     '%locale%'
